#ifndef CONTROLLEUR_GLOBAL_H
#define CONTROLLEUR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CONTROLLEUR_LIBRARY)
#  define CONTROLLEURSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CONTROLLEURSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CONTROLLEUR_GLOBAL_H
