#ifndef JEUXDEROLE_GLOBAL_H
#define JEUXDEROLE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(JEUXDEROLE_LIBRARY)
#  define JEUXDEROLESHARED_EXPORT Q_DECL_EXPORT
#else
#  define JEUXDEROLESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // JEUXDEROLE_GLOBAL_H
